/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.flipkart.marketplace.listings.schema.reverse.listing;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class order_policy extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7790640985981634929L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"order_policy\",\"namespace\":\"com.flipkart.marketplace.listings.schema.reverse.listing\",\"fields\":[{\"name\":\"independent_sellable\",\"type\":\"boolean\",\"presentationName\":\"Independently Sellable?\",\"description\":\"Whether this product can be sold independently.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public boolean independent_sellable;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public order_policy() {}

  /**
   * All-args constructor.
   * @param independent_sellable The new value for independent_sellable
   */
  public order_policy(java.lang.Boolean independent_sellable) {
    this.independent_sellable = independent_sellable;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return independent_sellable;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: independent_sellable = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'independent_sellable' field.
   * @return The value of the 'independent_sellable' field.
   */
  public java.lang.Boolean getIndependentSellable() {
    return independent_sellable;
  }

  /**
   * Sets the value of the 'independent_sellable' field.
   * @param value the value to set.
   */
  public void setIndependentSellable(java.lang.Boolean value) {
    this.independent_sellable = value;
  }

  /**
   * Creates a new order_policy RecordBuilder.
   * @return A new order_policy RecordBuilder
   */
  public static com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder newBuilder() {
    return new com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder();
  }

  /**
   * Creates a new order_policy RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new order_policy RecordBuilder
   */
  public static com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder newBuilder(com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder other) {
    return new com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder(other);
  }

  /**
   * Creates a new order_policy RecordBuilder by copying an existing order_policy instance.
   * @param other The existing instance to copy.
   * @return A new order_policy RecordBuilder
   */
  public static com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder newBuilder(com.flipkart.marketplace.listings.schema.reverse.listing.order_policy other) {
    return new com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder(other);
  }

  /**
   * RecordBuilder for order_policy instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<order_policy>
    implements org.apache.avro.data.RecordBuilder<order_policy> {

    private boolean independent_sellable;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.independent_sellable)) {
        this.independent_sellable = data().deepCopy(fields()[0].schema(), other.independent_sellable);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing order_policy instance
     * @param other The existing instance to copy.
     */
    private Builder(com.flipkart.marketplace.listings.schema.reverse.listing.order_policy other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.independent_sellable)) {
        this.independent_sellable = data().deepCopy(fields()[0].schema(), other.independent_sellable);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'independent_sellable' field.
      * @return The value.
      */
    public java.lang.Boolean getIndependentSellable() {
      return independent_sellable;
    }

    /**
      * Sets the value of the 'independent_sellable' field.
      * @param value The value of 'independent_sellable'.
      * @return This builder.
      */
    public com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder setIndependentSellable(boolean value) {
      validate(fields()[0], value);
      this.independent_sellable = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'independent_sellable' field has been set.
      * @return True if the 'independent_sellable' field has been set, false otherwise.
      */
    public boolean hasIndependentSellable() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'independent_sellable' field.
      * @return This builder.
      */
    public com.flipkart.marketplace.listings.schema.reverse.listing.order_policy.Builder clearIndependentSellable() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public order_policy build() {
      try {
        order_policy record = new order_policy();
        record.independent_sellable = fieldSetFlags()[0] ? this.independent_sellable : (java.lang.Boolean) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
