/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.flipkart.marketplace.listings.schema.reverse.listing;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class tax extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 585987049865053207L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"tax\",\"namespace\":\"com.flipkart.marketplace.listings.schema.reverse.listing\",\"fields\":[{\"name\":\"hsn\",\"type\":\"string\",\"presentationName\":\"HSN\",\"description\":\"Harmonized System Number as per GoI\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence hsn;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public tax() {}

  /**
   * All-args constructor.
   * @param hsn The new value for hsn
   */
  public tax(java.lang.CharSequence hsn) {
    this.hsn = hsn;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return hsn;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: hsn = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'hsn' field.
   * @return The value of the 'hsn' field.
   */
  public java.lang.CharSequence getHsn() {
    return hsn;
  }

  /**
   * Sets the value of the 'hsn' field.
   * @param value the value to set.
   */
  public void setHsn(java.lang.CharSequence value) {
    this.hsn = value;
  }

  /**
   * Creates a new tax RecordBuilder.
   * @return A new tax RecordBuilder
   */
  public static com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder newBuilder() {
    return new com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder();
  }

  /**
   * Creates a new tax RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new tax RecordBuilder
   */
  public static com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder newBuilder(com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder other) {
    return new com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder(other);
  }

  /**
   * Creates a new tax RecordBuilder by copying an existing tax instance.
   * @param other The existing instance to copy.
   * @return A new tax RecordBuilder
   */
  public static com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder newBuilder(com.flipkart.marketplace.listings.schema.reverse.listing.tax other) {
    return new com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder(other);
  }

  /**
   * RecordBuilder for tax instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<tax>
    implements org.apache.avro.data.RecordBuilder<tax> {

    private java.lang.CharSequence hsn;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.hsn)) {
        this.hsn = data().deepCopy(fields()[0].schema(), other.hsn);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing tax instance
     * @param other The existing instance to copy.
     */
    private Builder(com.flipkart.marketplace.listings.schema.reverse.listing.tax other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.hsn)) {
        this.hsn = data().deepCopy(fields()[0].schema(), other.hsn);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'hsn' field.
      * @return The value.
      */
    public java.lang.CharSequence getHsn() {
      return hsn;
    }

    /**
      * Sets the value of the 'hsn' field.
      * @param value The value of 'hsn'.
      * @return This builder.
      */
    public com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder setHsn(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.hsn = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'hsn' field has been set.
      * @return True if the 'hsn' field has been set, false otherwise.
      */
    public boolean hasHsn() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'hsn' field.
      * @return This builder.
      */
    public com.flipkart.marketplace.listings.schema.reverse.listing.tax.Builder clearHsn() {
      hsn = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public tax build() {
      try {
        tax record = new tax();
        record.hsn = fieldSetFlags()[0] ? this.hsn : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
