package io.hari.democonnectors.mysql;

import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.junit.Test;

import java.sql.*;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * @Author hayadav
 * @create 4/19/2021
 * https://zetcode.com/db/mysqljava/
 * https://www.baeldung.com/jdbc-batch-processing
 * https://www.jackrutorial.com/2018/03/spring-boot-batch-read-from-mysql-database-and-write-into-a-csv-file-tutorial.html
 */
@Slf4j
public class MySqlConnector {
    public static final String SCHEMA_NAME = "testdb";
    public static final String URL = "jdbc:mysql://localhost:3306/" + SCHEMA_NAME + "?useSSL=false";

    public static final String USERNAME = "root";
    public static final String PASSWORD = "hariom";

    public static final String SCHEMA_NAME2 = "testdb";
    public static final String URL2 = "jdbc:mysql://localhost:3306/" + SCHEMA_NAME2 + "?useSSL=false";
    public static final String SHOW_TABLES_SQL = "show tables";
    public static final String INSERT_EMP_SQL = "insert into emp(name) values(?)";

    @Test
    public void testConnection() {
        final Connection connection = createConnection();
        closeConnection(connection);
    }

    @SneakyThrows
    @Test
    public void testTableName() {
        final Connection connection = getConnection();
        readAllTables(connection);
        final Connection connection1 = getConnection();
        final List<String> tables = getAllTablesInsideSchema(connection1);
        System.out.println("tables = " + tables);
    }

    @Test
    public void testAllRowsInTable() {
        getAllRowsInTable();
    }

    @Test
    public void insertNewRow() {
        insertRowWithAllValues();
    }

    @Test
    public void insertNewRow2() {
        insertRowAutoGeneratedPK();
        insertMultipleRowsAutoGeneratedPKForLoop();
    }

    @Test
    public void testColumnMetadata() {
        getColumnInformation();
    }

    @SneakyThrows
    public Connection createConnection() {
        log.info("MySqlConnector.createConnection");
        final Connection connection = getConnection();
        final Statement connectionStatement = connection.createStatement();
        final ResultSet resultSet = connectionStatement.executeQuery("SELECT VERSION()");
        if (resultSet.next()) {
            System.out.println("resultSet.getString(1) = " + resultSet.getString(1));
        }
        resultSet.close();
        System.out.println("Connection info retrieved successfully :" + connection.getSchema());
        return connection;
    }

    @SneakyThrows
    public void closeConnection(Connection connection) {
        log.info("MySqlConnector.closeConnection");
        connection.close();
    }

    @SneakyThrows
    public void readAllTables(Connection connection) {
        final DatabaseMetaData connectionMetaData = connection.getMetaData();
        String[] table = {"TABLE"};
        final ResultSet resultSet = connectionMetaData.getTables(null, null, null, table);//working
//        final ResultSet resultSet = connectionMetaData.getTables(null, null, "%", table);//working
        List<String> tableNames = new LinkedList<>();
        while (resultSet.next()) {
            final String tableName = resultSet.getString("TABLE_NAME");
            tableNames.add(tableName);
        }
        System.out.println("tableNames = " + tableNames);
        connection.close();
    }

    @SneakyThrows
    public List<String> getAllTablesInsideSchema(final Connection connection) {
        final Statement statement = connection.createStatement();
        final ResultSet resultSet = statement.executeQuery(SHOW_TABLES_SQL);
        final List<String> tables = new ArrayList<>();
        while (resultSet.next()) {
            final String tableName = resultSet.getString(1);
            tables.add(tableName);
            log.info("tableName = " + tableName);
        }
        connection.close();
        return tables;
    }

    @SneakyThrows
    public void getAllRowsInTable() {
        final Connection connection = getConnection();
        final Statement connectionStatement = connection.createStatement();
        final ResultSet resultSet = connectionStatement.executeQuery("select * from emp");
        while (resultSet.next()) {
            final int firstCol = resultSet.getInt(1);
            final String secondCol = resultSet.getString(2);
            System.out.println(firstCol + " " + secondCol);
        }
        connection.close();
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USERNAME, PASSWORD);
    }

    @SneakyThrows
    public void insertRowWithAllValues() {
        final String sql = "insert into emp(id, name) values(?, ?)";
        final Connection connection = getConnection();
        final PreparedStatement preparedStatement = connection.prepareStatement(sql);
        preparedStatement.setInt(1, 4);
        preparedStatement.setString(2, "neha");
        final int executeUpdate = preparedStatement.executeUpdate();
        System.out.println("executeUpdate = " + executeUpdate);
    }

    @SneakyThrows
    public void insertRowAutoGeneratedPK() {
        final String sql = "insert into emp(name) values(?)";
        final Connection connection = getConnection();
//        final PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);//working
        final PreparedStatement preparedStatement = connection.prepareStatement(sql);//working
        preparedStatement.setString(1, "neha 2");
        final int executeUpdate = preparedStatement.executeUpdate();
        System.out.println("executeUpdate = " + executeUpdate);
        connection.close();
    }

    @SneakyThrows
    public void insertMultipleRowsAutoGeneratedPKForLoop() {
        final String sql = "insert into emp(name) values(?)";
        final Connection connection = getConnection();
        final PreparedStatement preparedStatement = connection.prepareStatement(sql);
        for (int i = 0; i < 10; i++) {
            preparedStatement.setString(1, "neha-" + i);
            final int executeUpdate = preparedStatement.executeUpdate();
            System.out.println("executeUpdate = " + executeUpdate);
        }
        connection.close();
    }

    /**
     * https://dev.mysql.com/doc/refman/5.6/en/information-schema-columns-table.html
     * <p>
     * SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT
     * FROM INFORMATION_SCHEMA.COLUMNS
     * WHERE table_name = 'tbl_name'
     * [AND table_schema = 'db_name']
     * [AND column_name LIKE 'wild']
     */
    @SneakyThrows
    public void getColumnInformation() {
        final Connection connection = getConnection();
        final Statement connectionStatement = connection.createStatement();
        String sql = "SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT " +
                "  FROM INFORMATION_SCHEMA.COLUMNS " +
                "  WHERE table_name = 'emp'";
        final ResultSet resultSet = connectionStatement.executeQuery(sql);
        while (resultSet.next()) {
            log.info("{} {} {} ", resultSet.getString(1), resultSet.getString(2), resultSet.getString(3));
        }
        connection.close();
    }

    @Test
    public void testCreateTable() {
//        final String table = createTableSQL("_new");
//        System.out.println("table = " + table);
        final String tableDDL = "create table emp_new3( " +
                "id int not null auto_increment, " +
                "name varchar(100), " +
                "primary key(id) " +
                ");";
        String tabl2 = "String myTableName = \"CREATE TABLE AgentDetail (\" \n" +
                "            + \"idNo INT(64) NOT NULL AUTO_INCREMENT,\"  \n" +
                "            + \"initials VARCHAR(2),\" \n" +
                "            + \"agentDate DATE,\"  \n" +
                "            + \"agentCount INT(64), \"\n" +
                "            + \"PRIMARY KEY(idNo))\";  ";
        System.out.println("tabl2 = " + tabl2);
        createNewTable(tableDDL);
    }

    @SneakyThrows
    private void createNewTable(String tableSQL) {
        final Connection connection = getConnection();
        final Statement statement = connection.createStatement();
        final ResultSet resultSet = statement.executeQuery(tableSQL);
        connection.close();
    }

    public String createDDLForInsertData() {
        final String table_name = "table_name";
        final String all_columns_list = "all_columns_list";//id, name, ...
        String allColumn = getAllColumnList(table_name);
        final String all_column_values = "all_column_values";
        String templateSQL = "insert into " + table_name + "(" + all_columns_list + ") values(" + all_column_values + ")";
        return templateSQL;
    }

    public void getAllTables() {

    }

    @SneakyThrows
    @Test
    public void testPageWise() {
        final List<String> tables = getAllTablesInsideSchema(getConnection());
        tables.stream().peek(t -> System.out.println("table : " + t))
                .forEach(table -> getPageWiseReadingData(table, "id", 0, 10));
    }

    @SneakyThrows
    public void getPageWiseReadingData(String tableName, String sortBy, int pageNumber, int perPageSize) {
//        final String sql = "select * from emp order by id limit 0, 3";//start from 0th index and total it will pick 3 item
        final String sql2 = "select * from " + tableName + " order by " + sortBy + " limit " + pageNumber + ", " + perPageSize;//start from 0th index and total it will pick 3 item

        final Connection connection = getConnection();
        final Statement statement = connection.createStatement();
        final ResultSet resultSet = statement.executeQuery(sql2);
        while (resultSet.next()) {
            final int anInt = resultSet.getInt(1);
            final String string = resultSet.getString(2);
            System.out.println(anInt + " " + string);
        }
        connection.close();
    }

    @Test
    public void testBatchStatement() {
        batchInsertDataUsingStatement();
    }

    @SneakyThrows
    public void batchInsertDataUsingStatement() {
        final Connection connection = getConnection();
        final Statement statement = connection.createStatement();
        statement.addBatch("insert into emp(name) values('hariom yadav')");
        statement.addBatch("insert into emp(name) values('hariom yadav2')");
        statement.addBatch("insert into emp(name) values('hariom yadav3')");
        statement.executeBatch();
        statement.close();
        connection.close();
    }

    @Test
    public void testBatchPreparedStatement() {
        batchInsertDataUsingPreparedStatement(27, 5);
    }

    @SneakyThrows
    public void batchInsertDataUsingPreparedStatement(final int totalRows, final int batchSize) {
        final Connection connection = getConnection();
        final PreparedStatement preparedStatement = connection.prepareStatement(INSERT_EMP_SQL);
        int count = 0;
        for (int i = 0; i < totalRows; i++) {
            count++;
            preparedStatement.setString(1, "mac book - " + i);
            preparedStatement.addBatch();
            if (count >= batchSize) {
                preparedStatement.executeBatch();
                count = 0;
            }
        }
        preparedStatement.executeBatch();//execute all sql
        preparedStatement.close();
        connection.close();
    }

    @Test
    public void testBatchThreadPool() {
        batchInsertDataUsingPreparedStatement2(17, 5);
    }

    @SneakyThrows
    public void batchInsertDataUsingPreparedStatement2(final int totalRows, final int batchSize) {
        final ExecutorService threadPool = Executors.newFixedThreadPool(4);
        final Connection connection = getConnection();
        final PreparedStatement preparedStatement = connection.prepareStatement(INSERT_EMP_SQL);
        final AtomicInteger count = new AtomicInteger(0);
        for (int i = 0; i < totalRows; i++) {
            count.getAndIncrement();
            preparedStatement.setString(1, "thinkpad-laptop - " + i);
            preparedStatement.addBatch();
            if (count.get() >= batchSize) {
                executeBatch(threadPool, preparedStatement);
                count.set(0);
            }
        }
        preparedStatement.executeBatch();//execute all sql
        connection.close();
    }

    private void executeBatch(final ExecutorService threadPool, final PreparedStatement preparedStatement) {
        threadPool.submit(() -> {
            try {
                preparedStatement.executeBatch();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        });
    }

    @Test
    public void testCloudDB() {
        cloudDbConnection();
    }

    @SneakyThrows
    public void cloudDbConnection() {
        final String username = "oizyqsewr5";
        final String password = "eFoJkeAxvz";
        final String server = "remotemysql.com";
        final String databaseSchemaName = username;
        final String url = "jdbc:mysql://" + server + ":3306/" + databaseSchemaName + "?useSSL=false";
        final Connection connection = DriverManager.getConnection(url, username, password);

        final Statement connectionStatement = connection.createStatement();
        final ResultSet resultSet = connectionStatement.executeQuery("SELECT VERSION()");
        if (resultSet.next()) {
            System.out.println("resultSet.getString(1) = " + resultSet.getString(1));
        }
        resultSet.close();
        System.out.println("Connection info retrieved successfully :" + connection.getSchema());
    }


    @SneakyThrows
    private String getAllColumnList(String table_name) {
        final Connection connection = getConnection();
        connection.close();
        return null;
    }

    @SneakyThrows
    public String createTableSQL(String suffix) {
        String sql = "select * from emp";

        final Connection connection = getConnection();
        final Statement statement = connection.createStatement();
        ResultSet resultSet = statement.executeQuery(sql);
        ResultSetMetaData metaData = resultSet.getMetaData();
        int columnCount = metaData.getColumnCount();
        String tableName = null;
        StringBuilder sb = new StringBuilder(1024);
        if (columnCount > 0) {
            final String dataTableName = metaData.getTableName(1);
            sb.append("Create table ").append(dataTableName + suffix).append(" ( ");
            System.out.println("sb = " + sb);
        }
        for (int i = 1; i <= columnCount; i++) {
            if (i > 1) sb.append(", ");
            String columnName = metaData.getColumnLabel(i);
            String columnType = metaData.getColumnTypeName(i);

            sb.append(columnName).append(" ").append(columnType);
            System.out.println("sb = " + sb);

            int precision = metaData.getPrecision(i);
            if (precision != 0) {
                sb.append("( ").append(precision).append(" )");
                System.out.println("sb = " + sb);
            }
        } // for columns
        sb.append(" ) ");
        System.out.println(sb.toString());
        return sb.toString();
    }
}
