appName: dropwizard template
location: "Bangalore, KA, India"
threadPoolConfig:
  threadPoolSize: 4


#common api or common asset access from root path : https://www.dropwizard.io/en/latest/manual/core.html#serving-assets
server:
  rootPath: /api/
  requestLog: # URI request in JSON format : {"requestTime":152,"protocol":"HTTP/1.1","method":"GET","contentLength":58,"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","uri":"/api/test-api","remoteAddress":"[0:0:0:0:0:0:0:1]","timestamp":1622170269170,"status":200}
    appenders:
      - type: console
        layout:
          type: access-json


# Logging settings.
logging:
  # default level of all logging, OFF, ERROR, INFO, DEBUG, WARN, TRACE, ALL
  level: INFO

  # Logger-specific levels, here we can override above level
  # USE CASE 1: one use case is off whole app LOG and make one resource log on to see only log from that resource
  # USE CASE 2: we can create log file and store all logs for a specific package , and same time we can show that package log on console log or exclude using "additive: true/false "
  loggers:
#    "resource.MyResource" : TRACE

    "resource.MyResource":
      level: TRACE
      # This line stops org.hibernate.SQL (or anything under it) from using the root logger
      additive: true # false means we will not show log on console & only show in below file
      appenders:
        - type : file
          currentLogFilename: ./log/example-sql.log
          archivedLogFilenamePattern: ./logs/example-sql-%d.log.gz
          archivedFileCount: 5
  appenders: # JSON logging : add maven dependency + below config
    - type: console
      layout:
        type: json #json, access-json(this will go inside server.requestLog.appenders)

#todo : testing pending : https://www.dropwizard.io/en/latest/manual/configuration.html#man-configuration-logging
metrics:
  reporters:
    - type: csv
      file: ./csv_reports/
